global:
  scrape_interval: 5s          # Сбор метрик каждые 5 секунд
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  # Метрики самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (метрики хоста)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Nginx Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Postgres Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Blackbox Exporter (проверка доступности сервисов)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://cms-nginx:80  # Проверка доступности nginx
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Дополнительные цели для blackbox (другие модули)
  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - cms-postgres:5432   # Проверка PostgreSQL
        - cms-php:9000        # Проверка PHP-FPM
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'windows-host'
    static_configs:
      - targets: ['host.docker.internal:9182']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

# remote_write в VictoriaMetrics + лейбл site=prod
remote_write:
  - url: http://victoriametrics:8428/api/v1/write
    write_relabel_configs:
      - target_label: site
        replacement: "prod"